# Generated by Django 2.2.9 on 2020-09-26 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200926_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='group_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
