# Generated by Django 2.2.9 on 2020-09-26 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20200926_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='posts',
        ),
        migrations.AddField(
            model_name='group',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
