from django.urls import path

from . import views
from .views import PostCreate

urlpatterns = [
    path("",
         views.index,
         name="index"),
    path("new/",
         views.create_post,
         name="post_new"),
    # path("new/",
    #      PostCreate.as_view(),
    #      name="post_new"),
    path("group/<slug:slug>/",
         views.group_posts,
         name="group"),
    path("follow/",
         views.follow_index,
         name="follow_index"),
    path("<str:username>/",
         views.profile,
         name='profile'),
    path("<str:username>/<int:post_id>/",
         views.post_view,
         name='post_detail'),
    path("<str:username>/<int:post_id>/edit/",
         views.post_edit,
         name='post_edit'),
    path("<username>/<int:post_id>/comment",
         views.add_comment,
         name="add_comment"),
    path("<username>/<int:post_id>/<int:comment_id>/edit",
         views.comment_edit,
         name="comment_edit"),
    path("<username>/<int:post_id>/<int:comment_id>/delete",
         views.comment_delete,
         name="comment_delete"),
    path("<str:username>/follow/",
         views.profile_follow,
         name="profile_follow"),
    path("<str:username>/unfollow/",
         views.profile_unfollow,
         name="profile_unfollow"),
]
